/**
 * Semantic types over the generated schema.
 *
 * `database.types.ts` is generated by `npm run db:types` and must never be
 * edited -- the next regeneration would silently discard the edit. Anything
 * hand-written about the schema lives here instead.
 *
 * Two things this file adds that a generator cannot know:
 *
 *   - readable names for the enums, so a signature says `CefrLevel` rather than
 *     `Database["public"]["Enums"]["cefr_level"]`;
 *   - the actual shape of the `jsonb` columns. Postgres types them as `json`
 *     and stops there; these are the shapes the app and the seed script have
 *     already agreed on, and writing them down is the only place that agreement
 *     is checked.
 */
import type { Database } from "./database.types";

export type { Database, Json } from "./database.types";

type DB = Database["public"];
type Enums = DB["Enums"];

export type CefrLevel = Enums["cefr_level"];
export type Contrast = Enums["contrast"];
export type SessionStage = Enums["session_stage"];
export type SpeakingMode = Enums["speaking_mode"];
export type CardState = Enums["card_state"];
export type ReviewMode = Enums["review_mode"];
export type Motivation = Enums["motivation"];
export type ShadowingStage = Enums["shadowing_stage"];

export type Tables<T extends keyof DB["Tables"]> = DB["Tables"][T]["Row"];
export type InsertOf<T extends keyof DB["Tables"]> = DB["Tables"][T]["Insert"];
export type UpdateOf<T extends keyof DB["Tables"]> = DB["Tables"][T]["Update"];

/* -------------------------------------------------------------------------- */
/* jsonb shapes                                                                */
/* -------------------------------------------------------------------------- */

/** `scenes.transcript`. Sentence-level timings, so tapping a line replays exactly that line (PRD F4). */
export type TranscriptSegment = {
  start_ms: number;
  end_ms: number;
  /** A character id from `characters` -- the cast is fixed (PRD 4.3). */
  character: string;
  en: string;
  es?: string;
};

/** `scenes.questions`. Spanish at A0-A1, English from A2 (PRD 4.5 taper). */
export type SceneQuestion = {
  q_es?: string;
  q_en?: string;
  options_es?: string[];
  options_en?: string[];
  answer: number;
};

/** `chunks.audio_urls`. PRD F2 requires at least two voices before publication. */
export type ChunkAudio = { voice_id: string; url: string; accent: string };

/** `minimal_pairs.audio`. Human recordings only (PRD 8.1B). */
export type PairAudio = { speaker_id: string; word: string; url: string };
